### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ipatka** [Moloch-Mystics/Baal#33]
Features that are not currently covered

### NFT
- [ ] Token URI creation

### Initialization
- [ ] Ensure setup can only be called once, on summon

### Membership
- [ ] Rage quit

### Proposals
- [ ] Sponsorship
- [ ] Delegated voting

### Baal only functions (outside of initialization)
- [ ] Share minting
- [ ] Loot minting
- [ ] convert shares to loot
- [ ] set periods
- [ ] Set flash loan config
- [ ] Set shamans
- [ ] Set guild tokens

### Shaman only functions
- [ ] Share minting & burning
- [ ] Loot minting & burning

### share mgmt
- [ ] ERC20 functions for shares
- [ ] Pausing share transfers
- [ ] Delegation of shares on first mint

### Flash loans
- [ ] flash loan functionality

**Comment by ipatka** [comment]
add test for this condition https://github.com/Moloch-Mystics/Baal/issues/36

**Comment by dekanbro** [comment]
issue clean up.
