### ISSUE TITLE
UX Feedback pt 2

### ISSUE THREAD

**Issue by wswarren12** [Moloch-Mystics/Baal#35]
* Add back a proposal velocity to processing to ensure some gap between processing for ragequits. 

* Add auto vote option to sponsor

* Update member action to allow for yeeting with ERC20 and make it so you could just send funds to an address and have the Shaman write.

**Comment by ipatka** [comment]
prefer no auto vote due to 'oh crap vote no on this'

**Comment by dekanbro** [comment]
issue clean up.
