### ISSUE TITLE
Transferrable Shares allows members to double vote

### ISSUE THREAD

**Issue by ameensol** [Moloch-Mystics/Baal#36]
you can attack it by:
> Alice vote yes on proposal #1
> Alice transfer shares to Bob
> Bob vote yes on proposal #1 (now with Alice's shares)
> Alice effectively double votes

**Comment by z0r0z** [comment]
this should be prevented by the comp-style checkpointing system. That is, Bob's receipt of Alice's shares won't count towards proposal #1, because Baal vote function checks Bob's balance at proposal creation time.
