### ISSUE TITLE
Allow Baals to use Safe as RQ-able treasury

### ISSUE THREAD

**Issue by ipatka** [Moloch-Mystics/Baal#45]

**Comment by ipatka** [comment]
generally improve RQ to use multisend https://github.com/Moloch-Mystics/Baal/blob/0c57812dbc6caa9e3d9d2cd729f9b11bfb0df80c/contracts/Baal.sol#L809

**Comment by ipatka** [comment]
Also add native gas token to RQ

**Comment by dekanbro** [comment]
issue clean up.
