### ISSUE TITLE
Remove guild tokens and instead have RQ pass in an array of token addresses

### ISSUE THREAD

**Issue by ipatka** [Moloch-Mystics/Baal#46]

**Comment by topocount** [comment]
Interested in taking this on. Would it be possible to get a bit more context on what "remove guild tokens" means here?

**Comment by ipatka** [comment]
So right now we store an array of whitelisted tokens

https://github.com/Moloch-Mystics/Baal/blob/b832a717b58f8c1b049e089f4f88e0fe7202579c/contracts/Baal.sol#L134

They are enabled/ disabled here: https://github.com/Moloch-Mystics/Baal/blob/b832a717b58f8c1b049e089f4f88e0fe7202579c/contracts/Baal.sol#L585

The only purpose of guild tokens array is to loop through them when people rage quit

https://github.com/Moloch-Mystics/Baal/blob/b832a717b58f8c1b049e089f4f88e0fe7202579c/contracts/Baal.sol#L825


Instead we could remove this array, and just have the user pass an array of token addresses to the contract when they want to rage quit

**Comment by topocount** [comment]
cool, this is a fun one

**Comment by ipatka** [comment]
resolved in denver branch
