### ISSUE TITLE
Scope Reduction + Feature Refinement

### ISSUE THREAD

**Issue by ameensol** [Moloch-Mystics/Baal#52]
My proposed updates (for my selfish use case). Note - some of these are covered in other issues. 

- remove flashloan
- add ragekick back → abstract ragequit so it doesn’t have to be msg.sender
- remove grace period shortcutting
- remove custom per-proposal voting periods (?)
- memberAction / setPeriod / setGuildTokens as shaman permissions
- init setting to permanently allow / disallow memberAction and/or setPeriods / setGuildTokens
- make loot its own ERC20 token (?) → should be easier bc don’t have to checkpoint votes
    - make a wrapper that calls into transferLoot
- add safeRagequit which omits some token addresses

**Comment by ipatka** [comment]
- [x] remove flashloan
- [ ] add ragekick back → abstract ragequit so it doesn’t have to be msg.sender
- [ ] remove grace period shortcutting
- [ ] remove custom per-proposal voting periods (?)
- [ ] memberAction / setPeriod / setGuildTokens as shaman permissions
- [ ] init setting to permanently allow / disallow memberAction and/or setPeriods / setGuildTokens
- [x] make loot its own ERC20 token (?) → should be easier bc don’t have to checkpoint votes (WIP)
- [ ] make a wrapper that calls into transferLoot
- [ ] add safeRagequit which omits some token addresses

**Comment by ipatka** [comment]
[] Add max expiry period
[] Add one way config locks

**Comment by ipatka** [comment]
- [ ] Add test function with hashOperation

**Comment by dekanbro** [comment]
issue clean up.
