### ISSUE TITLE
Permissions Blocks

### ISSUE THREAD

**Issue by ameensol** [Moloch-Mystics/Baal#53]
We should separate Baal permissions into categories which can be selectively assigned to specific shamans, and which can also be permanently locked from the outset.

setAdmin:
- pauseShares
- pauseLoot
- setGuildTokens
- unsetGuildTokens

setShares:
- mintShares
- burnShares
- mintLoot
- burnLoot
- convertSharesToLoot (if we keep this function)

setGovernance:
- votingPeriod (remove min/max)
- gracePeriod
- newOffering
- quorum (new param)
- winByPercent (new param)

quorum -> new governance param to require proposal yesVotes >= some % of totalShares (can be set to 0 to skip)
winByPercent -> new governance param to require yesVotes - noVotes >= some % of totalShares (can be set to 0 to skip)
^ both would be checked in processProposal

The permission system means we would either need 3 separate registries, or we could use a number to represent the total permissions, although this is a bit less legible. 

3 separate registries:
mapping(address => bool) public adminShamans;
mapping(address => bool) public sharesShamans;
mapping(address => bool) public governanceShamans;

Using a number:

E.g. 1 point for Admin, 2 points for shares, 4 points for governance
0 = no permission
1 = admin only
2 = shares only
4 = governance only
3 = admin + shares
5 = admin + governance
6 = shares + governance

**Comment by ipatka** [comment]
Should we use these same buckets for one way permission locks?

**Comment by ameensol** [comment]
Yes, I would think so.

**Comment by ameensol** [comment]
We could add view functions to help users decipher the numbers if we go that route:

```
function isAdmin(address shaman) view returns (bool) {
  let permission = permissions[shaman];
  return (permission == 1 || permission == 3 || permission == 5);
}

**Comment by dekanbro** [comment]
issue clean up.
