### ISSUE TITLE
Dual Factory System with CREATE

### ISSUE THREAD

**Issue by Ro5s** [Moloch-Mystics/Baal#6]
For Baal summoning, the following could help onboarding and give cost-effective options:

- Factory can do `new` construction of Baal contracts with summoning params (expensive deploy, cheaper TXs)
- Factory can do `clone` of Baal template (cheap deploy, expensive TXs)

in either case, this should use CREATE to deploy Baal to identical address on all EVM chains.

**Comment by Ro5s** [comment]
note: 

more recently we have imported OpenZeppelin template for ERC20 to represent Baal voting shares. This OZ template might need to be reworked in order to support minimal proxy-like cloning of Baal contracts from a factory.

**Comment by dekanbro** [comment]
issue clean up. using OZ Clones now which should have this
