### ISSUE TITLE
use native signer set

### ISSUE THREAD

**Issue by z0r0z** [Moloch-Mystics/Baal#81]
rather than design moloch v3 around gnosis safe framework, it can always be an append to gnosis safe framework and still choose to focus on voting module and not making treasury opinionated. See KALI mult-sig for contemporary suggestions for moloch v3 along these lines: https://github.com/kalidao/multi-sig

**Comment by dekanbro** [comment]
that would be great. If it supports Zodiac it should be able to plug into any multisig

**Comment by dekanbro** [comment]
issue clean up.
